#!/usr/bin/bash
# build all the project

# get current dir
CUR_DIR=`pwd`

# normal collect
COLLECT_DIR=$CUR_DIR/collect
PRETREAT_DIR=$CUR_DIR/pretreat
INSERT_DIR=$CUR_DIR/insert

cd $COLLECT_DIR
make -f Makefile

cd $PRETREAT_DIR
make -f Makefile

cd $INSERT_DIR
make -f Makefile


# parse module
HUAWEI_DIR=$CUR_DIR/huawei
NOKIA_DIR=$CUR_DIR/nokia
HUAWEI_A1_DIR=$CUR_DIR/huawei_a1

cd $HUAWEI_DIR
make -f Makefile

cd $NOKIA_DIR
make -f Makefile

cd $HUAWEI_A1_DIR
cmake .
make -f Makefile


# re-collect
RECOLLECTOR_DIR=$CUR_DIR/recollector

cd $RECOLLECTOR_DIR
make -f Makefile


# cleaner
CLEAN_DATA_PRETREAT_DIR=$CUR_DIR/cleaner/clean_data_pretreat

cd $CLEAN_DATA_PRETREAT_DIR
make -f Makefile


# log parser
LOG_PARSER_DIR=$CUR_DIR/log_parser

cd $LOG_PARSER_DIR
sh release.sh


# exception collect
COLLECT_EXCEPT_DIR=$CUR_DIR/collect_except

cd $COLLECT_EXCEPT_DIR
sh release.sh


# controller
CONTROLLER_DIR=$CUR_DIR/controller

cd $CONTROLLER_DIR
sh release.sh

