#!/usr/bin/bash
# clean all the project

# get current dir
CUR_DIR=`pwd`

# normal collect
COLLECT_DIR=$CUR_DIR/bill_parser/collect
INSERT_DIR=$CUR_DIR/bill_parser/gsm_i
PRETREAT_DIR=$CUR_DIR/bill_parser/pretreat
HUAWEI_DIR=$CUR_DIR/bill_parser/huawei
NOKIA_DIR=$CUR_DIR/bill_parser/nokia
HUAWEI_A1_DIR=$CUR_DIR/bill_parser/huawei_a1

cd $COLLECT_DIR
make -f Makefile clean

cd $INSERT_DIR
make -f Makefile clean

cd $PRETREAT_DIR
make -f Makefile clean

cd $HUAWEI_DIR
make -f Makefile clean

cd $NOKIA_DIR
make -f Makefile clean

cd $HUAWEI_A1_DIR
make -f Makefile clean

# recollect
RECOLLECT_DIR=$CUR_DIR/recollector/recollect
HUAWEI_DIR=$CUR_DIR/recollector/huawei
NOKIA_DIR=$CUR_DIR/recollector/nokia
HUAWEI_A1_DIR=$CUR_DIR/recollector/huawei_a1

cd $RECOLLECT_DIR
make -f Makefile clean

cd $HUAWEI_DIR
make -f Makefile clean

cd $NOKIA_DIR
make -f Makefile clean

cd $HUAWEI_A1_DIR
make -f Makefile clean

# cleaner
CLEAN_DATA_PRETREAT_DIR=$CUR_DIR/cleaner/clean_data_pretreat

cd $CLEAN_DATA_PRETREAT_DIR
make -f Makefile clean

# log parser
LOG_PARSER_DIR=$CUR_DIR/log_parser

cd $LOG_PARSER_DIR
sh clean.sh

# exception collect
COLLECT_EXCEPT_DIR=$CUR_DIR/collect_except

cd $COLLECT_EXCEPT_DIR
sh clean.sh

# controller
CONTROLLER_DIR=$CUR_DIR/controller

cd $CONTROLLER_DIR
sh clean.sh

