#!/bin/csh
source ~/.cshrc
perl /opt/BOCO.DAL/RT_MON/zj-bill-parser/release/collect_except/collect_except -r /opt/BOCO.DAL/RT_MON/zj-bill-parser/release/collect_except -c /opt/BOCO.DAL/RT_MON/zj-bill-parser/data/collect -p 10 -m -10
