#!/usr/bin/bash
# build all the project

# get current dir
CUR_DIR=`pwd`

# normal collect
COLLECT_DIR=$CUR_DIR/bill_parser/collect
INSERT_DIR=$CUR_DIR/bill_parser/gsm_i
PRETREAT_DIR=$CUR_DIR/bill_parser/pretreat
HUAWEI_DIR=$CUR_DIR/bill_parser/huawei
NOKIA_DIR=$CUR_DIR/bill_parser/nokia
HUAWEI_A1_DIR=$CUR_DIR/bill_parser/huawei_a1

cd $COLLECT_DIR
make -f Makefile

cd $INSERT_DIR
make -f Makefile

cd $PRETREAT_DIR
make -f Makefile

cd $HUAWEI_DIR
make -f Makefile

cd $NOKIA_DIR
make -f Makefile

cd $HUAWEI_A1_DIR
cmake .
make -f Makefile

# re-collect
RECOLLECT_DIR=$CUR_DIR/recollector/recollect
HUAWEI_DIR=$CUR_DIR/recollector/huawei
NOKIA_DIR=$CUR_DIR/recollector/nokia
HUAWEI_A1_DIR=$CUR_DIR/recollector/huawei_a1

cd $RECOLLECT_DIR
make -f Makefile

cd $HUAWEI_DIR
make -f Makefile

cd $NOKIA_DIR
make -f Makefile

cd $HUAWEI_A1_DIR
cmake .
make -f Makefile

# cleaner
CLEAN_DATA_PRETREAT_DIR=$CUR_DIR/bill_parser/cleaner/clean_data_pretreat

cd $CLEAN_DATA_PRETREAT_DIR
make -f Makefile

# log parser
LOG_PARSER_DIR=$CUR_DIR/bill_parser/log_parser

cd $LOG_PARSER_DIR
sh release.sh

# exception collect
COLLECT_EXCEPT_DIR=$CUR_DIR/bill_parser/collect_except

cd $COLLECT_EXCEPT_DIR
sh release.sh

# controller
CONTROLLER_DIR=$CUR_DIR/controller

cd $CONTROLLER_DIR
sh release.sh

